name: crypto_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State management(BLOC)
  flutter_bloc: ^9.1.1
  bloc_concurrency: 0.3.0

  #Dependency injection
  get_it: ^9.2.0

  #Simplify Equality Comparisons
  equatable: ^2.0.8

  #HTTP requests
  dio: ^5.9.1
  dio_smart_retry: 7.0.1

  #Logger
  talker_flutter: ^5.1.13
  talker_dio_logger: ^5.1.13
  talker_bloc_logger: ^5.1.13

  #Protect data
  envied: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
